before_script:
  - apt update
  - apt -y install ant maven openjdk-8-jdk openjdk-8-jre

compile:
  stage: build
  script:
    - mvn compile

test_argumentKalculusParser:
  stage: test
  script:
    - mvn test -Dtest=TestArgumentKalculusParser
  artifacts:
    when: on_failure
    expire_in: 7 days
    paths:
      - target/surefire-reports/TEST-*.xml
      - target/surefire-reports/*.txt

test_arguments:
  stage: test
  script:
    - mvn test -Dtest=TestArguments
  artifacts:
    when: on_failure
    expire_in: 7 days
    paths:
      - target/surefire-reports/TEST-*.xml
      - target/surefire-reports/*.txt

test_ast:
  stage: test
  script:
    - mvn test -Dtest=TestAst
  artifacts:
    when: on_failure
    expire_in: 7 days
    paths:
      - target/surefire-reports/TEST-*.xml
      - target/surefire-reports/*.txt

test_evaluator:
  stage: test
  script:
    - mvn test -Dtest=TestEvaluator
  artifacts:
    when: on_failure
    expire_in: 7 days
    paths:
      - target/surefire-reports/TEST-*.xml
      - target/surefire-reports/*.txt

test_kalculusParser:
  stage: test
  script:
    - mvn test -Dtest=TestKalculusParser
  artifacts:
    when: on_failure
    expire_in: 7 days
    paths:
      - target/surefire-reports/TEST-*.xml
      - target/surefire-reports/*.txt

package:
  stage: deploy
  script:
    - mvn package -Dmaven.test.skip=true
  artifacts:
    when: on_success
    expire_in: 30 days
    paths:
      - fkalculus*standalone.jar