before_script:
  - apt update
  - apt -y install ant maven openjdk-8-jdk openjdk-8-jre

compile:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test
  artifacts:
    when: on_failure
    expire_in: 7 days
    paths:
      - target/surefire-reports/TEST-*.xml
      - target/surefire-reports/*.txt


package:
  stage: deploy
  script:
    - mvn package -Dmaven.test.skip=true
  artifacts:
    when: on_success
    expire_in: 30 days
    paths:
      - fkalculus*standalone.jar