
build:
    stage: build

    before-script:
      - apt update
      - apt -y install maven

    script: mvn compile

test:
    stage: test

    before-script:
      - apt update
      - apt -y install maven

    script: mvn test
