before_script:
  - apt update
  - apt -y install maven openjdk-8-jdk openjdk-8-jre

compile:
  stage: build
  script:
    - mvn compile

unit_test:
  stage: test
  script:
    - mvn test
  artifacts:
    when: on_failure
    expire_in: 7 days
    paths:
      - target/surefire-reports/TEST-*.xml
      - target/surefire-reports/*.txt
